Fix typo
timber/timber pull request #2363
Opened 2020-11-05 07:59 UTC by 19h47

Remove unnecessary quotes in line 321: 

```php
	 * <a href="{{ item.link }}" {{ item.is_external or item.is_target_blank ? 'target="_blank"' }}">
```

2020-11-05 19:53 UTC, acobster submitted a review, later dismissed
Looks good to me!

2020-11-05 20:01 UTC, gchtr requested changes
I figured the same error appears some lines above:
https://github.com/timber/timber/pull/2363/files#diff-2484f91d742ea05a569b75d47cd670b0b6a547f6485de421558865178ac85df3R315

@19h47 Would you mind removing that type there as well?

2020-11-05 20:40 UTC, 19h47 commented
Hello @gchtr, I just corrected. Thank you, didn't see it 😅

2020-11-05 20:45 UTC, gchtr approved these changes
Cool, thanks! That’s why we have pull requests, so that there’s at least 4 👀 looking at it 😉.

2020-11-06 13:49 UTC, jarednova commented
LGTM! The failing Travis test with webp in PHP 7.2 is unrelated here (and corrected in the 2.x branch)

2020-11-06 13:49 UTC, merged