#2382 Optimizations for "How to split into chunks flexible content fields"
timber/timber pull request #2388
Opened 2020-12-30 10:07 UTC by gchtr

**Ticket**: #2382

I added some optimizations for #2368 

- Moved new content from section about Reapeater Fields to Flexible Content Field section.
- Used `include()` function instead of `include` statement, as this is recommended by Twig, see https://twig.symfony.com/doc/3.x/tags/include.html.
- Added some syntax optimizations.

2020-12-30 10:26 UTC, 19h47 commented
Didn't know about the `include` function from Twig 3 either, thank you! 😮

2020-12-30 10:27 UTC, gchtr commented
> Didn't know about the `include` function from Twig 3 either, thank you! 😮

It’s also available in Twig 2: https://twig.symfony.com/doc/2.x/functions/include.html.

2020-12-30 15:08 UTC, jarednova requested changes
Looks good! Just one suggestion in regards to use of names. If I were building a theme, I'd probably keep everything named the same ("blocks") — but I think we should make super-clear to readers that there's no "magic" in naming things the same and they can use whatever names they need/want.

2020-12-30 15:08 UTC, jarednova commented on docs/v2/integrations/advanced-custom-fields.md
> +Assuming your block Twig files are inside a **blocks** folder:
```suggestion
Assuming your block Twig files are inside a **my_blocks** folder within your other Twig file directory (ex: `my_theme/views/my_blocks`).
```

2020-12-30 15:08 UTC, jarednova commented on docs/v2/integrations/advanced-custom-fields.md
> +    {{ include("blocks/#{ block.acf_fc_layout|sanitize ) }.twig", {
```suggestion
    {{ include("my_blocks/#{ block.acf_fc_layout|sanitize ) }.twig", {
```

2020-12-30 15:08 UTC, jarednova commented on docs/v2/integrations/advanced-custom-fields.md
> +The [sanitize](https://timber.github.io/docs/v2/guides/filters/#sanitize) filter will slugify the block name. Consider this example for a Flexible Content Field named `credit` containing a `text` fie
```suggestion
The [sanitize](https://timber.github.io/docs/v2/guides/filters/#sanitize) filter will slugify the block name. Consider this example for a Flexible Content Field named `credit` containing a `text` field, inside the **my_blocks/photo.twig** file:
```

2020-12-30 15:21 UTC, 19h47 commented
Totally agreed. No "where do you put this folder" question

2020-12-30 15:48 UTC, gchtr commented
@jarednova I agree, we can make this clearer, but I’m always a little hesitant about using "my" in examples. I wouldn’t use `my_blocks` as a name for anything that I code myself. I’m sure it adds to the notion of "you can actually choose a name for this", but I think it’s not good practice for actually naming things. I also see that lots of developers copy-paste code from the documentation as it is. So I’d rather use real world code examples than examples where you’d have to rename stuff before using it.

But, maybe I’m all wrong 😊. Maybe if I’ve yet missed that using "my" is some best practice that’s established in the developer community.

> but I think we should make super-clear to readers that there's no "magic" in naming things the same and they can use whatever names they need/want.

Wouldn’t it be clear enough if we mention that you can name the folder as you want? Maybe like this:

`Assume your block Twig files are inside a folder within your other Twig template directory. For example, if you used a folder named **blocks**, then that would be the **wp-content/themes/example-theme/views/blocks** folder.`

2020-12-30 16:55 UTC, jarednova commented
@gchtr I definitely take `my_` as a "you can actually choose a name for this, but I think it’s not good practice for actually naming things." Though, agreed on the copy-and-pasted tendencies out there. As long as the "magic" problem is solved for, your solution of `Assume your block Twig files are inside a folder within your other Twig template directory. For example, if you used a folder named **blocks**, then that would be the **wp-content/themes/example-theme/views/blocks** folder` is totally 👍  w me!

2021-01-03 20:08 UTC, gchtr commented
@jarednova Cool, so I guess we’re on the same page here. I’ve updated the documentation once again a little in [`24c790a` (#2388)](https://github.com/timber/timber/pull/2388/commits/24c790ac33038add222bd381dde71eaaebfd4fe9). I hope it’s clearer now, even without using "my".

2021-01-04 13:39 UTC, jarednova approved these changes
LGTM!

2021-01-04 13:39 UTC, merged