Fix User entity
timber/timber pull request #2690
Opened 2022-12-13 08:54 UTC by nlemoine

## Issue

Setting public properties for user meta fields results in `{{ user.first_name }}` to return null. Because those properties are not `WP_User` properties and thus not imported.

## Solution

Remove public properties matching user meta so `__call` in `Timber\Core` is actually called.

## Impact

None.

## Usage Changes

You can now do `{{ user.first_name }}`, `{{ user.last_name }}`, etc.

## Testing

Just changed the test with description to ensure this works fine.

2022-12-29 15:58 UTC, gchtr requested changes
In the Upgrade Guide to 2.0, we advise to use `meta()` instead of directly accessing properties: https://timber.github.io/docs/v2/upgrade-guides/2.0/#meta.

To make it possible to use `{{ user.first_name }} or `{{ user.last_name }}`, I would add new methods on `Timber\User` instead. Here’s an example for the `first_name()` method.

```php
public function first_name(): string {
    return $this->meta( 'first_name' );
}
```

This way, we are explicit about where these values are coming from. And we will still have a reference for how to access these values in the documentation, as they will still be listed under https://timber.github.io/docs/v2/reference/timber-user/.

What do you think? If you want, I can add the methods.

2022-12-31 13:52 UTC, nlemoine commented
Hey @gchtr, 

I would personally leave it as it is. There are so many metas for users I'm afraid we won't be able to create methods for all of them, more precisely, we might not want to be exhaustive here. I think we can't stand half way here (some metas have direct shortcut methods and some don't), it would be more consistent if we adopt a stricter approach: no shortcut methods for metas, use `meta` instead.

Also note that `WP_User` is not behaving like other `WP_` objects (`WP_Post`, `WP_Term`, etc.). It's the only one that gets metas with magic `__get`.

2023-01-03 17:34 UTC, gchtr commented
> Hey @gchtr,
> 
> I would personally leave it as it is. There are so many metas for users I'm afraid we won't be able to create methods for all of them, more precisely, we might not want to be exhaustive here. I think we can't stand half way here (some metas have direct shortcut methods and some don't), it would be more consistent if we adopt a stricter approach: no shortcut methods for metas, use `meta` instead.

Huh, yes, you’re right. That would really be an exhaustive list. I added some documentation for how to access user values in [`4d2575f` (#2690)](https://github.com/timber/timber/pull/2690/commits/4d2575f84e287322b3ab3109e8c44a1908fb8435).

> Also note that `WP_User` is not behaving like other `WP_` objects (`WP_Post`, `WP_Term`, etc.). It's the only one that gets metas with magic `__get`.

The other objects also get meta values through the `__get` magic. This functionality is still here for backwards compatibility, but is discouraged. Or am I missing something?

2023-01-03 17:36 UTC, gchtr approved these changes
This looks good to me. I added the relevant changes in the Upgrade Guide in [`473839b` (#2690)](https://github.com/timber/timber/pull/2690/commits/473839bf1bef4815e55811c3016c2f1ed1874afc).

As soon as the checks go green, I’ll merge this.

2023-01-03 20:58 UTC, merged