Add `AllowDynamicProperties` attribute
timber/timber pull request #2698
Opened 2023-01-11 22:27 UTC by mcaskill

## Issue

Dynamic (non-explicitly declared) properties are deprecated as of PHP 8.2 and are expected to become a fatal error in PHP 9.0.

As you may have noticed in the CI logs, this generates a lot of noise both in error logs and test run logs.

## Solution

To reduce noise this pull request adds the `#[AllowDynamicProperties]` attribute to the [`Core`](src/Core.php) class.

## Considerations

Ideally, a magic `__set()` method should be added which will require adding a catch-all data property to store the non-declared fields.

```php
/**
 * Store dynamic meta fields.
 *
 * @var array<string, mixed>
 */
private $fields = [];

/**
 * Magic setter for dynamic meta fields, for convenience in Twig views.
 *
 * This method is not meant to be called directly.
 *
 * @example
 * ```php
 * $post = Timber\Post::get( get_the_ID() );
 *
 * $post->favorite_darkside_track = 'Any Colour You Like'
 * ```
 * ```twig
 * {# Since this property does not exist explicitly on the Post class,
 *    it will dynamically dispatch the magic __get() method with an argument
 *    of "favorite_darkside_track" #}
 * <span>Favorite <i>Dark Side of the Moon</i> Track: {{ post.favorite_darkside_track }}</span>
 * ```
 * @link https://secure.php.net/manual/en/language.oop5.overloading.php#object.set
 *
 * @param string $field The name of the property being mutated.
 * @param mixed $valuee The value to assign.
 *
 * @return void
 */
public function __set($field, $value)
{
    $this->fields[$field] = $value;
}
```

## Related

- [wordpress/wordpress#c033058](https://github.com/WordPress/WordPress/commit/c03305852e7e40e61cad5798eba9ebc3b961e27a)

2023-01-12 08:17 UTC, nlemoine requested changes
H @mcaskill!

Thanks for this PR, I noticed those warnings myself and was about to take care of this.

There's still some dynamic properties issues on the co-authors integration, would mind handle them?

2023-01-12 16:09 UTC, mcaskill commented
Hi @nlemoine 

> There's still some dynamic properties issues on the co-authors integration, would mind handle them?

All other dynamic properties deprecations are related to third-party plugins which are out of Timber's control.

While looking for dynamic properties in the Co-Authors integration, I noticed that the [Upgrade to 2.0](docs/v2/upgrade-guides/2.0.md) mentions that [support for Co-Authors Plus was removed in January 2020](https://github.com/timber/timber/commit/ffd474d0e3485db4b488abf6deae6fa61239b64d#diff-9a0786fa7e0e9bfb55892c6028a2dacdcb9d9cbf65901415d36b5eda37eafb26R28-R32).

2023-01-12 16:15 UTC, gchtr commented
> While looking for dynamic properties in the Co-Authors integration, I noticed that the [Upgrade to 2.0](docs/v2/upgrade-guides/2.0.md) mentions that [support for Co-Authors Plus was removed in January 2020](https://github.com/timber/timber/commit/ffd474d0e3485db4b488abf6deae6fa61239b64d#diff-9a0786fa7e0e9bfb55892c6028a2dacdcb9d9cbf65901415d36b5eda37eafb26R28-R32).

Yep, support was initially removed. But there’s a pull request to fix that notice, because we still support CoAuthors: https://github.com/timber/timber/pull/2684.

2023-02-21 07:00 UTC, gchtr approved these changes
I think we’re good to go here. Thanks so much for leading the way, @mcaskill!

I don’t see any warnings in files that we can control ourselves, except for some float-string to int precision errors in ImageDimensions.php. But I already saw that errors like these will be captured by PHPStan in other pull requests.

2023-02-21 12:02 UTC, nlemoine commented
LGTM! thanks @mcaskill

2023-02-21 13:05 UTC, nlemoine approved these changes

2023-02-21 13:06 UTC, merged

2023-04-25 20:34 UTC, drzraf commented
Could you please backport to 1.x ?

2023-06-13 17:36 UTC, danFWD commented
> Could you please backport to 1.x ?

I second this. The way I’ve been adding properties to the $context for years now has now created hundreds of deprecated notices in my sites after upgrading to PHP 8.2. Perhaps I was doing it wrong all along (according to the PHP open-source committee tasked with making these changes), but that doesn’t change the fact that it would be almost impossible to de-tangle it from my sites if and when it becomes a fatal error. 

Appreciate your hard work on this plugin, it is literally indispensable to me.