docs: Documented transform_value filter/parameter
timber/timber pull request #2846
Opened 2023-11-19 19:10 UTC by Levdbas

Related:

- #2811

## Issue
The new default behavior to not transform meta values to Timber objects anymore was not documented. 

## Solution
Update the ACF documentation on how to opt-in to this behavior globally or on a field-by-field basis

## Impact
Better understanding of the internal workings of field value transforms.

## Usage Changes
no

## Considerations
I think this behavior was default in v1 right? Shouldn't we add this to the Upgrade to 2.0 guide as well under meta?

## Testing
no

2023-11-23 07:37 UTC, gchtr commented
I think we could write it more clearly that if you don’t use the transform filter, ACF will just return the default. But if you wanted to have Timber objects automatically return based on the field type, then you would have to use the transform value.

There’s a defined list of field types that we transform. Maybe we could turn that into a list so developers could see which field types would be transformed into what?

https://github.com/timber/timber/blob/ee467c650e51d042a04d9107f35239cbc566d4d7/src/Integration/AcfIntegration.php#L252-L302

> I think this behavior was default in v1 right?

Timber v1 didn’t convert anything.

We started out by adding transforming values in 2.x by default, but then realized that it would probably better if this was an opt-in functionality. Here’s the pull request where all the discussion happened: https://github.com/timber/timber/pull/2397.

> Shouldn't we add this to the Upgrade to 2.0 guide as well under meta?

Yes, please!

2023-11-23 08:48 UTC, Levdbas commented
Tnx for the feedback, I will iterate on this soon!

2023-12-05 15:36 UTC, Levdbas commented
Alright, worked on the guide for a bit more and added all the fields that can be transformed in a table. Regarding the upgrade guide, since this is a new feature, should it still be added in the migration guide?

2023-12-07 11:36 UTC, gchtr requested changes
Thanks a lot for taking this on. I have only some minor improvements.

2023-12-07 11:36 UTC, gchtr commented on docs/v2/integrations/advanced-custom-fields.md
> +|user     | `Timber::get_users`         |
```suggestion
The values of the following field types will be transformed into Timber/PHP objects when using transforms:

| Field type | Returns  |
|---------|---------|
| File    | `Timber\Attachment`         |
| Image    | `Timber\Image`         |
| Gallery    | array of `Timber\Post`         |
| Date picker     |  `DateTimeImmutable`       |
| Date time picker     |  `DateTimeImmutable`       |
| Post object     | array of `Timber\Post` objects         |
| Relationship     | array of `Timber\Post` objects         |
| Taxonomy     | array of `Timber\Term` objects         |
| User     | array of `Timber\User` objects         |
```

2023-12-07 11:36 UTC, gchtr commented on docs/v2/integrations/advanced-custom-fields.md
> +### Transform  values to Timber/PHP objects
```suggestion
### Transform values to Timber/PHP objects
```

2023-12-07 11:36 UTC, gchtr commented on docs/v2/integrations/advanced-custom-fields.md
> +But sometimes you might want to transform values directly into Timber/PHP objects. For example, if you have a relationship field, you might want to transform the values in `Timber\Post` objects.
```suggestion
But sometimes you might want to transform values directly into Timber/PHP objects. For example, if you have a relationship field, you might want to transform the values into `Timber\Post` objects.
```

2023-12-07 11:36 UTC, gchtr commented on docs/v2/integrations/advanced-custom-fields.md
> +```
```suggestion
**functions.php**

```php
add_filter('timber/meta/transform_value', '__return__true');
```
```

2023-12-12 18:24 UTC, Levdbas commented
Good suggestions @gchtr , they are applied!

2023-12-13 08:24 UTC, gchtr approved these changes

2023-12-13 08:47 UTC, merged