Fix dynamic properties warnings
timber/timber pull request #2860
Opened 2023-12-04 05:18 UTC by trsteel88

Related:

- https://github.com/timber/timber/issues/2793

## Issue
This removes the warnings that flood a site on newer versions of PHP

## Solution
Implement the `#[\AllowDynamicProperties]` attribute. This is not a BC break as older versions of PHP would see this as a comment and ignore it.

## Impact
None.

2024-01-06 10:23 UTC, gchtr requested changes
Thanks for the pull request!

In Timber 2.0, we also have `#[\AllowDynamicProperties]` on `Timber\PostType`.

https://github.com/timber/timber/blob/7992eeed2039851ae705e0fa52545eabbc1d8293/src/PostType.php#L11

Because `Timber\PostType` doesn’t extend `Timber\Core`, I think we should add it there as well.

2024-01-06 10:26 UTC, trsteel88 commented
Good catch @gchtr. That's been updated in this PR

2024-01-15 21:16 UTC, trsteel88 commented
Any chance of getting this merged and tagged @gchtr?

2024-01-25 09:20 UTC, gchtr approved these changes

2024-01-25 09:56 UTC, gchtr commented
> Any chance of getting this merged and tagged @gchtr?

Yes, working on it. Just had to fix some tests and add testing for 8.2 to confirm that all Dynamic Property Warnings in Timber are actually gone.

2024-01-26 09:27 UTC, nlemoine approved these changes
all good 👍

2024-01-26 11:32 UTC, merged

2024-01-31 13:46 UTC, gchtr commented
This is now released in https://github.com/timber/timber/releases/tag/1.24.0

2024-02-05 05:29 UTC, trsteel88 commented
Thanks @gchtr