Update PostsIterator.php
timber/timber pull request #2918
Opened 2024-02-08 14:45 UTC by rubas

Related: #2917 

## Issue
`$post` can be `null`, which breaks the code.

2024-02-08 15:05 UTC, nlemoine commented
Thank you @rubas for this PR. 

We still support PHP 7.4 so `$post?->setup();` syntax will not work. Can you adapt your PR to match 7.4 requirements?

2024-02-08 15:53 UTC, rubas commented
`protected null|Post $last_post;`  

The support for union type was only introduced in PHP 8.0.

2024-02-08 15:59 UTC, rubas commented
The failed coding standard test is outside of this PR. I'm happy to push a fix...


```php
1) tests/test-timber-cache.php

    ---------- begin diff ----------
@@ -329,7 +329,7 @@
         $clear = $loader->clear_cache_timber(Timber\Loader::CACHE_OBJECT);
         $this->assertTrue($clear);
         $works = true;
-      
+
         if (isset($wp_object_cache->cache[Timber\Loader::CACHEGROUP])
             && !empty($wp_object_cache->cache[Timber\Loader::CACHEGROUP])) {
             $works = false;
    ----------- end diff -----------


Applied checkers:

 * PhpCsFixer\Fixer\Whitespace\NoWhitespaceInBlankLineFixer
```

2024-02-08 16:06 UTC, Levdbas commented
This might fix https://github.com/timber/timber/issues/2859 as well?

2024-02-08 16:21 UTC, nlemoine commented
for coding standards, you just need to run `composer run cs:fix`. But you can leave the failing test file or fix it. We'll take care of it later.

2024-02-08 17:07 UTC, rubas commented
> Thank you @rubas for taking this on. This might fix #2859 as well?

Correct. This is the same bug.

2024-02-08 20:20 UTC, nlemoine requested changes
Thanks @rubas. This is almost good for me.

Can you add the nullable type to `$last_post` and a test case for this?

2024-02-08 20:20 UTC, nlemoine commented on src/PostsIterator.php
> +    protected $last_post;
You still use a nullable type here.
```suggestion
    protected ?Post $last_post;
```

2024-02-23 11:32 UTC, nlemoine approved these changes
This is all good, thanks @rubas!

2024-02-23 11:35 UTC, merged